parser: '@typescript-eslint/parser'
env:
    browser: true
    es6: true
    node: true
    jest: true
    jquery: true
extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    - prettier
plugins:
  - react
  - react-hooks
rules:
    no-duplicate-imports:
      - error
    no-self-compare:
      - error
    no-shadow:
      - off
    '@typescript-eslint/no-shadow':
      - error
      - { builtinGlobals: false, hoist: 'any', ignoreOnInitialization: true, allow: ['InputProps'] }
    eqeqeq:
      - error
    no-console:
      - error
    max-params:
      - error
    no-eval:
      - error
    no-return-await:
      - error
    no-var:
      - error
    prefer-const:
      - error
    'react-hooks/rules-of-hooks':
      - error
overrides:
    [
        {
            files: ['*.ts', '*.tsx'],
            parserOptions: { project: ['./tsconfig.json'] },
            rules:
                {
                    '@typescript-eslint/no-misused-promises':
                        [
                            'error',
                            {
                                'checksVoidReturn':
                                    {
                                        'attributes': false,
                                        'properties': false,
                                    },
                            },
                        ],
                },
        },
        {
            files: ['**/*.stories.*'],
            rules: { 'import/no-anonymous-default-export': 'off', 'no-console': 'off' },
        },

    ]
