version: '3.3'

services:
  backend:
    volumes:
     - static_volume:/app/staticfiles
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "8000:8000"

  frontend:
    volumes:
      - frontend:/app/build
    build:
      context: ./frontend

  nginx:
    volumes:
     - static_volume:/app/staticfiles
     - frontend:/var/www/frontend
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
    static_volume:
    frontend:
