# Generated by Django 4.2.5 on 2023-11-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_management", "0002_diagram_created_at_group_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("IN_PROGRESS", "In progress"),
                    ("PRESENTING", "Presenting"),
                    ("DONE", "Done"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("ANALYSING", "Analysing"),
                    ("MODELLING", "Modelling"),
                    ("DONE", "Done"),
                ],
                default="ANALYSING",
                max_length=20,
            ),
        ),
    ]
